### ISSUE TITLE
Problem with cell background colour

### ISSUE THREAD

**Issue by yamakhalah** [LaurentiuUngur/LUExpandableTableView#14]
Hey,

First and foremost, thanks for that great lib. I just have a little problem which i hope you could fix.

https://puu.sh/xTQfo/fcc5272bec.png

When i click on the header, sub cells appear but before having the same background color than the header background color, the background color of each cells are white.

It resides in a very ugly effect when i expand the header. Could you fix that ?

Thanks

**Comment by LaurentiuUngur** [comment]
Hi,

Thank you for using this lib !

Please try setting cell's `backgroundColor` and cell's `contentView.backgroundColor` to the same as header's bg color. Maybe you can set table view's bg color to `clear`. The issue appears most probably due to automatic row height or incorrect estimated row height. Maybe you can use a fixed height for cells instead.

Thanks !

**Comment by yamakhalah** [comment]
Fixed my case ! Thanks
